### ISSUE TITLE
Don't send mails when there was nothing to do

### ISSUE THREAD

**Issue by tik-stbuehler** [mvo5/unattended-upgrades#172] opened 2019-02-25 10:08 UTC
Since updating a few hosts to debian buster I'm getting daily unattended-upgrades mails from those hosts even when there was nothing to do:

```
Subject: unattended-upgrades result for [...]: SUCCESS

Unattended upgrade result: No packages found that can be upgraded 
 unattended and no pending auto-removals 

Unattended-upgrades log:
Checking if system is running on battery is skipped. Please install powermgmt-base package to check power status and skip installing updates when the system is running on battery.
Checking if connection is metered is skipped. Please install python3-gi package to detect metered connections and skip downloading updates.
Initial blacklist : 
Initial whitelist: 
Starting unattended upgrades script
Allowed origins are: [...]
No packages found that can be upgraded unattended and no pending auto-removals
```

I'm not looking forward to getting 150 of those each day. I think those mails should not be sent in a default configuration, so this is imho a separate issue from #104.

It would be appreciated if a fix would make it to buster.

(I guess c9c9dfe73ba339f2c75de8ea7b1c987ea9286fe9 might be the one that broke it.)

**Comment by rbalint** [comment] 2019-03-22 19:57
Fixed in https://github.com/mvo5/unattended-upgrades/pull/175 , Buster inclusion depends on unlocking u-u 1.11 in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924935 .
I just cherry-picked the fix to Ubuntu Disco.

**Closed** 2019-03-22 19:57 UTC

**Comment by stbuehler** [comment] 2019-03-23 12:58
Thanks!

**Comment by jannh** [comment] 2019-03-25 17:10
It seems like the fix from #175 did not make it into the 1.11 and subsequently also not into debian testing/buster. Would it be possible to cherry-pick the fix into buster or do you think that a potential 1.12 will eventually make it into buster? Thank you very much for your efforts!!

**Comment by rbalint** [comment] 2019-03-26 10:09
@jannh Since Debian is in full freeze this non-RC fix is unlikely to be accepted to Buster. :-( On the brighter side 1.12 will work on Buster thus you can just upgrade u-u to the version from unstable.

**Comment by lafrech** [comment] 2019-05-15 17:55
That's really a pity.

I'd consider this behaviour a regression, and #175 a bug fix. Is it not possible to cherry-pick #175 into Buester as a bug fix, even if it is not a RC-bug fix?

If #175 is too broad, is it worth filing a bug in Debian BTS for a fix to this specific issue in a smaller changeset?

I'm not a Debian policies expert. Please excuse my if this is a silly question.

**Comment by rbalint** [comment] 2019-05-15 18:03
@lafrech I asked the Debian Release Team to consider accepting 1.12 or parts of it to Buster in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=928108

**Comment by lafrech** [comment] 2019-05-15 19:13
Great. I checked bugs related to unattended-upgrades but I didn't see this bug report as it is filed against release.debian.org. Sorry about the noise.
